-- Create factura_digital table to almacenar comprobantes equivalentes a la factura física
CREATE TABLE IF NOT EXISTS factura_digital (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  venta_id text UNIQUE,
  nro_factura varchar(100) NOT NULL UNIQUE,
  timbrado varchar(30) NOT NULL,
  establecimiento varchar(5) NOT NULL,
  punto_expedicion varchar(5) NOT NULL,
  secuencia integer NOT NULL,
  condicion_venta varchar(20) NOT NULL DEFAULT 'CONTADO',
  fecha_emision timestamptz NOT NULL DEFAULT now(),
  moneda varchar(10) NOT NULL DEFAULT 'PYG',
  total_exentas numeric(12,2),
  total_gravada_5 numeric(12,2),
  total_gravada_10 numeric(12,2),
  total_iva_5 numeric(12,2),
  total_iva_10 numeric(12,2),
  total numeric(12,2) NOT NULL,
  total_iva numeric(12,2),
  total_letras text,
  pdf_path text,
  hash_pdf varchar(128),
  qr_data text,
  numero_control varchar(64),
  estado_envio varchar(30) NOT NULL DEFAULT 'PENDIENTE',
  enviado_a text,
  enviado_en timestamptz,
  intentos integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT factura_digital_venta_fk FOREIGN KEY (venta_id) REFERENCES venta(id) ON DELETE SET NULL,
  CONSTRAINT factura_digital_secuencia_unica UNIQUE (timbrado, establecimiento, punto_expedicion, secuencia)
);
